### ISSUE TITLE
IPv6 ist nicht sichtbar

### ISSUE THREAD

**Issue by templis** [tueit/it_management#102]
Es sollte irgend eine Möglichkeit geben, zu erkennen, dass da auch eine ipv6 Adresse hinterlegt ist

![2020-05-18 16_58_48-khst-lin-srv01 - khst-lin-srv01](https://user-images.githubusercontent.com/9048398/82228591-98884e00-9929-11ea-9edf-3680987a67a7.png)

**Comment by musketeer90** [comment]
Ist bereits so (siehe test.erp)
