### ISSUE TITLE
Remove Projekt from "Make Timesheet Popup"

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#109]
custom field project can be removed from the "make timesheet popup" in Issue.

**Comment by wojosc** [comment]
As we have set the field project in issue as mandetory beeing able to manipulate the project at this point is not necessary. The space could be used to something like trip instead (to be considered and discussed first...)

**Comment by canlann** [comment]
Projectview shows to be useful when e.g. issue has no project set, of field does not show due to permissions.
