### ISSUE TITLE
Changes to NIC Table

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#110]
maybe use NICs in Config Item similar to Contact Card on Customer. Please discuss.

@templis @canlann @miaschu

![grafik](https://user-images.githubusercontent.com/22279621/87146644-926c7900-c2ab-11ea-9a7f-400313bfb062.png)

**Comment by canlann** [comment]
Compare #122

**Comment by wojosc** [comment]
@canlann wenn Du sowas umgesetzt hast und das auf Deiner Testinstanz lief, dann am besten einfach n paar Screenshots hier rein ballern. Dann "lebt" das ein bisschen mehr.
