### ISSUE TITLE
fetch-from -> IT Checklist in Issue

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#113]
When fetching IT Checklist the whole IT Management Table is overwritten. List Items coming from IT Checklist should be added to the existing table and not replace existing elements.

**Comment by canlann** [comment]
Maybe this can be solved with the new DialogAPI from the ERPNext Documentation ( Compare #119 ).

**Comment by canlann** [comment]
To fix this issue we need to build a custom solution.

**Comment by canlann** [comment]
Bug am Beispiel Task behoben.

**Comment by canlann** [comment]
- [ ] Bug für Issue beheben vgl. Task
