### ISSUE TITLE
2 Suggestions

### ISSUE THREAD

**Issue by skaysurfer** [tueit/it_management#116]
It would be great if the Items from IT Management appear on Customerform on the Dashoarb like Projekts 

Also on the Menü when Customer logs in to ERPNEXT, it wouldt be nice if he cann see his Solutions, ConfigItems and so on...

Is it possible?

Also i would like to have the data of the items earchable by the default search on ERPNEXT.
Example, if i search for a hostname of one pc "kdpc01" (which is a configuration item) would list the data of that item in the searchresults

**Comment by wojosc** [comment]
@skaysurfer I have created a feautre request on the matter:
https://github.com/tueit/it_management/issues/124

Also I have been able to add the search option. Try this: https://handbuch.tueit.de/books/erpnext-benutzerhandbuch/page/suchen

**Comment by wojosc** [comment]
@skaysurfer I closed this on basis of my last post.
