### ISSUE TITLE
Links in Dashboard of Task

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#117]
![image](https://user-images.githubusercontent.com/22279621/90977459-0a35f080-e546-11ea-9b15-55c072241ed3.png)

Please move Materialrequest under new Category "Material"

Add Issue to Dashboard in Category Support

**Comment by canlann** [comment]
![grafik](https://user-images.githubusercontent.com/11473213/91701124-2275c300-eb77-11ea-9369-c5036a23b2da.png)
