### ISSUE TITLE
Add "Get Items from" to Task

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#119]
Inside DocType Task we need the function to "get items from" -> IT Checklist

**Comment by canlann** [comment]
Siehe ERPNext Dokumentation DialogAPI

**Comment by canlann** [comment]
Bug #113 still exists.

**Comment by wojosc** [comment]
Button does not work. @canlann Please check.

![get_item_no_pop_up](https://user-images.githubusercontent.com/22279621/108759695-fa2ab800-754c-11eb-9a41-1dff7d246488.gif)

**Comment by wojosc** [comment]
is fixed.
