### ISSUE TITLE
DocType Configuration Item Redesign

### ISSUE THREAD

**Issue by canlann** [tueit/it_management#121]
![grafik](https://user-images.githubusercontent.com/11473213/91707626-5e615600-eb80-11ea-90b6-734a4f999939.png)

![grafik](https://user-images.githubusercontent.com/11473213/91707724-8a7cd700-eb80-11ea-941b-92fe14d4c4d0.png)

![grafik](https://user-images.githubusercontent.com/11473213/91707818-b1d3a400-eb80-11ea-8346-cb54209160dd.png)

![grafik](https://user-images.githubusercontent.com/11473213/91708088-1d1d7600-eb81-11ea-91d0-54662a9023d4.png)

**Comment by canlann** [comment]
Vgl. Vorgang zu Projekt in Doctype Anfrage in IT Management

**Comment by wojosc** [comment]
https://github.com/tueit/it_management/blob/master/it_management/it_management/doctype/configuration_item/configuration_item.json
