### ISSUE TITLE
Add Trip to Dashboard

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#123]
Please add a link in the dashboard to Trip in 

- [x] Issue
- [x] Task
- [x] Event

![image](https://user-images.githubusercontent.com/22279621/91881957-951f9500-ec82-11ea-9900-090c9c38c3eb.png)

**Comment by wojosc** [comment]
remember to add backlinks to the DocType Trip

**Comment by canlann** [comment]
> remember to add backlinks to the DocType Trip

Do you mean add a link field in Doctype Issue/Task/Event for Trip?

**Comment by canlann** [comment]
For the Dashboard of Doctype Event I found the following articles:

https://github.com/frappe/frappe/pull/4331 // This seems possible

https://frappeframework.com/docs/user/en/basics/doctypes/actions-and-links // Using the UI from v 12.1 on

https://discuss.erpnext.com/t/add-doctype-on-dashboard/27673  // Manually DOM-Insertion with Custom API

**Comment by canlann** [comment]
**Solution:** https://github.com/frappe/frappe/pull/8336

**Comment by canlann** [comment]
**Solved**
