### ISSUE TITLE
Customer Dashboard

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#124]
the possibility to make Configuration Items etc. available for customers.

**Comment by canlann** [comment]
![image](https://user-images.githubusercontent.com/11473213/98231976-64e3c380-1f5d-11eb-9782-d5e9fce540b2.png)

**Comment by wojosc** [comment]
@canlann I meant something different here :)

Customer Dashboard in this case would be a login for customers where they can see all the elements you have marked in yellow.

What I meant was this: https://handbuch.tueit.de/books/erpnext-benutzerhandbuch/page/mein-konto

Here we could give customers access to all their linked IT Management Items.

The information you have built into the DocType customer can be used in IT Landscape though...
https://github.com/tueit/it_management/issues/158

**Comment by canlann** [comment]
Done
![image](https://user-images.githubusercontent.com/11473213/98662964-c2ef1d00-2348-11eb-9b40-0fa69a61d3f9.png)

Also added Button in IT Management Settings:
For every customer create default landscape

**Comment by canlann** [comment]
@wojosc 

Nach dem 20.11 Update einmal durchführen:
![image](https://user-images.githubusercontent.com/11473213/98670633-4281e980-2353-11eb-882c-2c0ed27437e6.png)

**Comment by canlann** [comment]
Removed every Backling from Customer Dashboard and added Solution and IT Landscape Backlink.
