### ISSUE TITLE
Installing on v10 error

### ISSUE THREAD

**Issue by Helkyd** [tueit/it_management#13]
Trying to install on v10...
![15715740020875742596694655440474](https://user-images.githubusercontent.com/20396898/67159423-5d468200-f33c-11e9-8177-954e30c258df.jpg)

What to do?

**Comment by wojosc** [comment]
Sorry, no idea. Maybe this helps:
https://discuss.erpnext.com/t/document-attached-to-child-table-must-be-a-dict-or-basedocument-not-class-str/36542

**Comment by wojosc** [comment]
Closing this as we are focusing on running the app in v12.
