### ISSUE TITLE
DocType Configuration Item Multiselect not found

### ISSUE THREAD

**Issue by kaplan-michael** [tueit/it_management#132]
Hello 
I noticed that in process of updating erpNext and modules, The step 'The Updating DocTypes for it_management ' failed with 
'pymysql.err.InternalError: (1170, "BLOB/TEXT column 'description' used in key specification without a key length")'

after removing it_management, update was successful. After update I Installed it_management back , and noticed this error message "DocType Configuration Item Multiselect not found"  attached screenshot

<img width="409" alt="Screenshot 2020-09-23 at 12 30 18" src="https://user-images.githubusercontent.com/16418072/94001521-e3fbae80-fd98-11ea-9270-450585fdb483.png">

I believe this issue was introduced in commit aa489d60fb8adff61b23943008904a0711b74f91

As checking out to a084118e091a238b2479cbbd2b3058b92a8e5777 and rebuilding works fine.

**Comment by wojosc** [comment]
Hi @kaplan-michael thank you for posting the error. We have added some stuff in a new "release" which isn't clean at the moment.

We are looking for a time slot to release a new version in which this will be fixed.

You can also create that doctype on your instance manualy and then it should work...

Stay tuned :)

**Comment by kaplan-michael** [comment]
Hey @wojosc OK, Thanks for the info. I'm fine with being on last "working" commit. for now. 
Thanks for the effort with this plugin :-) 
Looking forward to it. 
If I can be of any help, let me know :-)

**Comment by wojosc** [comment]
Hi @kaplan-michael we are work on a clean release management which should help us avoiding these troubles.

You can help us alot just by using the App and providing is with feedback. Thank you!

**Comment by canlann** [comment]
Resolved... (There were custom doctypes locally that were not reflected in the repo).

**Comment by wojosc** [comment]
@kaplan-michael this was resolved with:

https://github.com/tueit/it_management/commit/72cbd85ebd5c3d80b08f0652990c1c623f440dda

https://github.com/tueit/it_management/commit/6a4895a5eefd69399c3653234446723a55e5b10d

https://github.com/tueit/it_management/commit/495080ba5b7232f1f6155fa77e6af2dd0723952c

https://github.com/tueit/it_management/commit/3a83df7a872d5ac13961fa3a91504e1ca05cb251

**Comment by kaplan-michael** [comment]
@wojosc Thanks for the update on this.
