### ISSUE TITLE
Make -> Timesheet in Doctype Project 

### ISSUE THREAD

**Issue by canlann** [tueit/it_management#137]
Make -> Timesheet in Doctype Project change and make similar to Make -> Timesheet in Doctype Task

**Comment by wojosc** [comment]
Please remove "make -> timesheet" from project.

**Comment by canlann** [comment]
@wojosc What if somebody does common task, such as clean up of descriptions, task,...

**Comment by wojosc** [comment]
@canlann it is a common problem that people "just do work" instead of following the the tasks assigned. One only does work on assigned tasks. If one has no task assigned one has to ask for one to work one.
