### ISSUE TITLE
add IT Management Table to Issue

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#14]
please add IT Management Table to Issue. Add new Section IT Management after section Details. Content of this table should also be transfered to IT when created.

On creation of IT Ticket we need a quick entry with:

- Project (Projects)
- Customer
- Contact
- Assignee (ToDo)
- Due Date (ToDo)

Add field (Typ Link) with IT Ticket in Issue
Change Issue status to closed.

**Comment by joelios** [comment]
![grafik](https://user-images.githubusercontent.com/26505401/67463609-05f92800-f642-11e9-80fe-323bcfec83c7.png)

**Comment by wojosc** [comment]
Das hat nur etwas mit dem ITT-0000010 zu tun. Ich habe ein neues Issue und ein neues Ticket erstellt. Da kommt das Problem nicht mehr auf.

Nun frage ich mich aber, ob die Kommentarfunktion sinnvoll ist, da ja Tickets auch gelöscht werden können und die Verlinkung dann verweist. Was sagst Du?


"Add field (Typ Link) with IT Ticket in Issue" das haben wir nun gar nicht drin. Es stellt sich nun die Frage, ob es sinn macht, hierfür ein Feld zu

**Comment by wojosc** [comment]
![image](https://user-images.githubusercontent.com/22279621/67464028-e0b8e980-f642-11e9-8f0e-1a7cc1262367.png)
Hier siehst Du auch noch, dass er zwar den Status setzt, diesen aber nicht "richtig" setzt.

**Comment by joelios** [comment]
Ich habe soeben die aufgetauchten Bugs behoben. Nun sollte alles wie gewünscht funktionieren.
Bezüglich "Add field (Typ Link) with IT Ticket in Issue"; das stimmt, dieses Feld ist nicht enthalten. Ich hatee genau den selben Gedanken (Löschen von Ticket nicht möglich aufgrund Linkfeld in Issue). Ich habe es als Vorschlag so gelöst, dass im Issue ein Kommentar mit einem Hyperlink auf das IT Ticket, und im IT Ticket ein Kommentar mit einem Hyperlink auf den ursprünglichen Issue erstellt wird. Was hälst Du davon? Du kannst es gerne Testen, die änderungen sind mit dem nachfolgenden Commit im Develop Branch.

**Comment by wojosc** [comment]
Please move the IT Management Table section above the Details section and also unfold.

**Comment by joelios** [comment]
Done
