### ISSUE TITLE
Create Report for "Local Area Network" and retire DocType

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#140]
an overview of all subnets in a location is the equivalent to a local are network. I have created a separate DocType for this purpose containing a table in which subnets can be populated. It shows, that this can be done by a custom Report which shows all subnets in a location.

As an effect Local Area Network will be retired. We will create a custom report called "Local Area Network" to fill it'S purpose.

**Comment by canlann** [comment]
For this purpose I added the Location fields to Subnet...
@wojosc Should location be mandatory in Subnet?
![image](https://user-images.githubusercontent.com/11473213/101157683-c9f90a80-362a-11eb-8299-03e93e23c411.png)

**Comment by wojosc** [comment]
no, mandetory not needed.
