### ISSUE TITLE
make Opportunity from Issue

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#142]
Please add Opportunity in make drop-down in Issue and task.

Opportunity should have reference fields to issue, task and project (consider using "fetch from").

**Comment by canlann** [comment]
field party_name in opportunity does not take value from issue or task... bug in frappe. probably because party_name is dynamic field

**Comment by canlann** [comment]
- [ ] takeover field party_name and opportunity_from -> remove both
- [ ] instead add field issue and task to opportunity and takeover
