### ISSUE TITLE
Add Task to "everywhere"

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#147]
As we would like to work more task oriented (rather that project oriented) we would like to have a linke field in all DocTypes where we can link project. These are (as far as I am aware of):

- [ ] Sales Order, 

- [ ] Sales Invoice, 

- [ ] Purchase Order, 

- [ ] Delivery Note, 

- [ ] Purchase Receipt, 

- [ ] Issue, 

- [ ] Material Request,

often the field is inside the Item Table. The DocType is then called e.g. "Delivery Note Item".

The Task field should always have a filter to Project

**Comment by canlann** [comment]
@wojosc 

> linke field in all DocTypes where we can link project

Work more task oriented but have a link field to project? Sure you didn't mean ... a link field to task ...
