### ISSUE TITLE
Dashboard Backlings not working with Multiselect

### ISSUE THREAD

**Issue by canlann** [tueit/it_management#148]
The Backlinks from the Doctype Solution to e.g. a Config Items do not appear in the Dashboard if Solution is linked as a Multiselect in the Dashboard itself.

**Comment by wojosc** [comment]
@canlann der ist da in ner Untertabelle oder?

**Comment by canlann** [comment]
Bei Frappe Issue eröffnet https://github.com/frappe/frappe/issues/11857

**Comment by canlann** [comment]
Deleted the fields for multiselect tables (Solution, Contact and Configuration Item) in Configuration Item Doctype
