### ISSUE TITLE
IT Checklist align table sizes or show informations behind the dots

### ISSUE THREAD

**Issue by templis** [tueit/it_management#150]
![2020-10-29 12_22_36-pulsmacher _ Rechner Tausch - ANFRG-20-01994](https://user-images.githubusercontent.com/9048398/97611700-cb755880-1a16-11eb-93e0-d1b9a73b67b6.png)

**Comment by canlann** [comment]
@templis sprech mich mal drauf an. Bei mir sieht die Tabelle in IT Checklist ganz anders aus

**Comment by templis** [comment]
@canlann mach mal eine Anfrage auf, dann klick auf "Get Items form" -> Checklist
Daraufhin geht ein neues Fenster auf. In dem Fenster siehst du oben beschriebenes Problem.
Sorry, hätte ich besser beschreiben können.

**Comment by canlann** [comment]
@templis Also dein tip ist sicher gold wert nur leider gilt das nur für die tabellen in standard doctypes. dieser get_it_checklist dialog ist vollständig eigenhändig von libracore entwickelt.

**Comment by canlann** [comment]
@templis btw. konnte das lösen ... kommt mit dem nächsten update
