### ISSUE TITLE
Dashboard Links in Item

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#152]
Please add Dashboard section IT Management with links to Configuration Item and Licence:
![image](https://user-images.githubusercontent.com/22279621/97903548-80718300-1d3f-11eb-85ad-6a2bbf31223e.png)

**Comment by canlann** [comment]
@wojosc Neither in Config Item nor in Licence it is possible to reference an article. closing issue, but added fundation in it_management app for dashboard items.

**Comment by wojosc** [comment]
@canlann There is a DocType Link to "Item" in Configuration Item:
![image](https://user-images.githubusercontent.com/22279621/98256009-58bc2e00-1f7e-11eb-9fd1-67917ac52fab.png)

Maybe this needs renaming to work?

**Comment by canlann** [comment]
Renaming field name to item_code in Licence and Configuration Item will do the trick
