### ISSUE TITLE
Umstellung Felder.

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#153]
![image](https://user-images.githubusercontent.com/22279621/98107858-651b8a80-1e9b-11eb-87e2-dd3d7c173344.png)

@Marius wie du schon einmal vorgeschlagen hattest...

**Comment by canlann** [comment]
The filter in Quick Entries currently not supported. There is a possible solution here:
https://discuss.erpnext.com/t/how-to-run-a-custom-script-in-quick-entry/39122/6
