### ISSUE TITLE
User Account Type not necessary?

### ISSUE THREAD

**Issue by canlann** [tueit/it_management#166]
In Doctype User Account wouldn't it be better to Link Type to Software instead of an own Doctype?

**Comment by wojosc** [comment]
@canlann which Software would you link a google Account to?

**Comment by canlann** [comment]
@wojosc IT Software mit Titel Google Account
Bsp.:
![image](https://user-images.githubusercontent.com/11473213/107621384-745a6300-6c56-11eb-9be1-143fa4def732.png)

**Comment by wojosc** [comment]
this does not make any sense to me. Are you trying to say a google account is software?
