### ISSUE TITLE
Experiments: Web View

### ISSUE THREAD

**Issue by canlann** [tueit/it_management#171]
https://www.agiliq.com/blog/2018/07/frappe-web-pages/

https://frappeframework.com/docs/user/pt/tutorial/web-views

https://discuss.erpnext.com/t/frappe-tutorial-web-views-issue/19991

Last but not least:
https://github.com/gaurav-naik/webview-erpnext

**Comment by wojosc** [comment]
@canlann what are you on about here? :)
