### ISSUE TITLE
Add Filter to Landscape

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#184]
in List view there should be Filters for Customer.

Also when using the Link field in a different docType customer should be visible and searchable

**Comment by canlann** [comment]
- [x]  in List view there should be Filters for Customer.

- [ ] Also when using the Link field in a different docType customer should be visible and searchable @wojosc please make clear

**Comment by canlann** [comment]
- [ ] Add Customer Name to IT Landscape with fetch from
- [ ] Also when using the Link field in a different docType customer should be visible and searchable
