### ISSUE TITLE
"bench migrate" fails with syntax error

### ISSUE THREAD

**Issue by mahescho** [tueit/it_management#189]
In the file:

./apps/it_management/it_management/it_management/doctype/software_instance/software_instance_dashboard.py

a comma is missing what leads to a syntax error.

    def get_data():
        return {
            'fieldname': 'software_instance',
            'non_standard_fieldnames': {
                    'Issue': 'dynamic_name',    <--- missing
                    'Task': 'dynamic_name'
            },

**Comment by wojosc** [comment]
@mahescho thank you for helping fixing!

https://github.com/tueit/it_management/commit/9233d8798839afca8b0ea0e71743506c5131e491
