### ISSUE TITLE
remove Customer Filter in Issue and add Filter via Table

### ISSUE THREAD

**Issue by canlann** [tueit/it_management#195]
![image](https://user-images.githubusercontent.com/11473213/108505512-ce42d480-72b7-11eb-912a-8681220f440e.png)

Preferred solution is to set filter based on Customer in Base-DocType in Document field in IT Management Table.

**Comment by canlann** [comment]
Vgl. #45

**Comment by canlann** [comment]
Fehler konnte auf der Entwicklungsumgebung nicht Repliziert werden, es wurde jedoch die Reihenfolge der SQL-Abfrage anhand des idx, d.h. anhand der Position in der IT Management Table, aufsteigend sortiert.

**Comment by wojosc** [comment]
@canlann ich glaub du bist hier im falschen Issue?! :)

**Comment by canlann** [comment]
@wojosc yoyo

**Comment by wojosc** [comment]
![image](https://user-images.githubusercontent.com/22279621/109305563-348ea080-783e-11eb-99a1-5823b6179c00.png)
