### ISSUE TITLE
Add DocType IT Backup

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#20]
Please add docType IT Backup.

If you have any good ideas on how to link to Configuration Items, Solutions or maybe even Software Instances let me know.
![grafik](https://user-images.githubusercontent.com/22279621/67401105-f381de80-f5ae-11e9-9e69-6bfbe05e1ac4.png)

**Comment by joelios** [comment]
> If you have any good ideas on how to link to Configuration Items, Solutions or maybe even Software Instances let me know.

Maybe you can use dynamic link analog to Contact and/or address?
