### ISSUE TITLE
timesheet in dashboard of issue went missing

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#202]
seems we removed this by accident with our last update?
![image](https://user-images.githubusercontent.com/22279621/109609897-4c12a580-7b2c-11eb-935c-64173f03aa40.png)

**Comment by wojosc** [comment]
@reggaetuna kriegst Du das schon gelöst?

**Comment by reggaetuna** [comment]
Habe das gestern mal angeschaut, halbe Urlaubstage sind schon drin, jedoch immer nur einer pro Zeitraum. Könnte mehr Felder für halbe Urlaubstage hinzufügen, falls das aber in Code auf >1 festgelegt ist also max 1 halber pro Urlaubsbuchung müsste man das direkt im ERP_HR_Doytype_Holiday ändern und als branch übernehmen, für zukünftige Updates.

Liebe grüße  

Gesendet von Mail für Windows 10

Von: Wolfram Schmidt
Gesendet: Montag, 8. März 2021 09:30
An: tueit/it_management
Cc: reggaetuna; Mention
Betreff: Re: [tueit/it_management] timesheet in dashboard of issue wentmissing (#202)

@reggaetuna kriegst Du das schon gelöst?

**Comment by reggaetuna** [comment]
@wojosc Well known issue...
https://discuss.erpnext.com/t/cur-frm-dashboard-add-transactions-doesnt-work-properly/54885/3
