### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by samjaninf** [tueit/it_management#208]
Hi,
When I try to install this app into a site it stops after giving this message:
```
Installing it_management...
Updating DocTypes for it_management : [========================================] 100%
Updating customizations for Maintenance Schedule
Updating customizations for Issue
Updating customizations for Customer
Updating customizations for Opportunity
Updating customizations for Delivery Note Item
Updating customizations for Purchase Order
Updating customizations for Maintenance Visit
Updating customizations for IT Service Report
Updating customizations for Task
Updating customizations for Project
An error occurred while installing it_management:
<b>Configuration Item</b> is an invalid Data field.<br><br>Only Options allowed for Data field are:<br><ul><li>Email</li><li>Name</li><li>Phone</ul>
```
When I run uninstall-app everything uninstalls properly, but I'm then left with issues in the front end such as:
![it_management-erpnext](https://user-images.githubusercontent.com/6589200/114449915-58fecc00-9ba3-11eb-8d05-eb2ab3df4d0d.png)

Any solution?

**Comment by canlann** [comment]
@wojosc Did you remove the Configuration Item from Project?

**Comment by samjaninf** [comment]
> @wojosc Did you remove the Configuration Item from Project?

No I did not. I didn't know I had to do this. How do I go about doing that?

**Comment by canlann** [comment]
@samjaninf Hey Sam, I was asking wojosc. It is possible he removed this accidentally. I will inform you as soon as possible, once the problem has been resolved.

**Comment by samjaninf** [comment]
> @samjaninf Hey Sam, I was asking wojosc. It is possible he removed this accidentally. I will inform you as soon as possible, once the problem has been resolved.

Oh, sorry. Thanks for looking into this.

**Comment by wojosc** [comment]
We have a custom field Configuration Item in Project:
![grafik](https://user-images.githubusercontent.com/22279621/115013743-b94a8200-9eb1-11eb-9965-0ceb2061e689.png)
As the field type is data this probably only exists because of some error we might have had due to linking issues.

Please try and create the same custom field and try reinstall and let me know if that works.

@canlann and I will look into the issue and push a solution asap.

Thank you for posting the Issue - Have a great day!

**Comment by samjaninf** [comment]
I tried, adding/removing that field from the Project DocType but the install was still incorrect. Also I did find the IT Landscape link in the Project and Task DocTypes and once I removed those linked fields as well as the Configuration Item, and that allowed me to get back into the Project and Task dashboard.

But it did not allow me to install the project.

**Comment by skaysurfer** [comment]
hey guys,
i also get the errror on my fresh installed Vm with debian 10 and frappe/erpnext version 13.

i took a while, but the installation was successfully.
then i download and install the it_management app and get the same error.

nevertheless i finished the installation prozess and add the app to my default site1.local 
i cant find a app dashboard but am able to start the doctypes and can place links on the v13 daschboard 

i dont know if the error still make problems. will see if i try to use the app.

a bench update throws also an error:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 101, in <module>
    main()
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ayerpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ayerpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ayerpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ayerpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ayerpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ayerpnext/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ayerpnext/frappe-bench/env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/commands/site.py", line 300, in migrate
    skip_search_index=skip_search_index
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/migrate.py", line 75, in migrate
    sync_customizations()
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/modules/utils.py", line 97, in sync_customizations
    sync_customizations_for_doctype(data, folder)
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/modules/utils.py", line 153, in sync_customizations_for_doctype
    validate_fields_for_doctype(doctype)
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 686, in validate_fields_for_doctype
    validate_fields(meta)
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 997, in validate_fields
    validate_data_field_type(d)
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 951, in validate_data_field_type
    frappe.msgprint(text_str + df_options_str, title="Invalid Data Field", raise_exception=True)
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 403, in msgprint
    _raise_exception()
  File "/home/ayerpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 359, in _raise_exception
    raise ValidationError(msg)
frappe.exceptions.ValidationError: <b>Naming Series</b> is an invalid Data field.<br><br>Only Options allowed for Data field are:<br><ul><li>Email</li><li>Name</li><li>Phone</ul>

**Comment by wojosc** [comment]
Hi @samjaninf @skaysurfer 
I justed installed IT Management 21.03 on a v13 Instance. Please retry the installation using the following branche and let me know if those errors are gone .Thanks.
![grafik](https://user-images.githubusercontent.com/22279621/115429337-9b5b8500-a203-11eb-86e8-f67cafb45bfe.png)

fyi @canlann @reggaetuna

**Comment by samjaninf** [comment]
@wojosc Hi, I installed with `bench get-app https://github.com/tueit/it_management --branch 21.03` I tried the install, but I get a different error:

![image](https://user-images.githubusercontent.com/6589200/115486118-fd2be700-a223-11eb-9c2f-f640ada91cf6.png)

We do not have any other apps installed other than frappe and erpnext. Could it be something about our install?

**Comment by wojosc** [comment]
Hi,

No this error also needs be fixed from my side. I'll look into it. Stay tuned!

**Comment by wojosc** [comment]
@samjaninf have changed this: https://github.com/tueit/it_management/blob/21.03/it_management/it_management/custom/timesheet.json

please try again.

**Comment by samjaninf** [comment]
Hey @wojosc. I seem to still be getting a very similar issue as before.

I uninstalled the it_management app, and re installed it:
```
bench get-app https://github.com/tueit/it_management.git --branch 21.03
INFO:bench.app:Getting app it_management
$ git clone https://github.com/tueit/it_management.git --branch 21.03 --depth 1 --origin upstream
Cloning into 'it_management'...
remote: Enumerating objects: 339, done.
remote: Counting objects: 100% (339/339), done.
remote: Compressing objects: 100% (219/219), done.
remote: Total 339 (delta 202), reused 174 (delta 114), pack-reused 0
Receiving objects: 100% (339/339), 160.30 KiB | 3.82 MiB/s, done.
Resolving deltas: 100% (202/202), done.
INFO:bench.app:installing it_management
$ ./env/bin/pip install -q -U -e ./apps/it_management 
$ bench build --app it_management
yarn run v1.22.4
$ FRAPPE_ENV=production node rollup/build.js --app it_management
Production mode
✔ Built js/moment-bundle.min.js
✔ Built js/libs.min.js

Building it_management assets...

EMPTY_BUNDLE : Generated an empty bundle
✔ Built js/itm_utils.js
✨  Done in 0.888s
Done in 4.39s.
$ sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
```

Then I tried installing it into the siite using `bench --site <site name> install-app it_management` which results in:
![Screenshot_20210423_140237](https://user-images.githubusercontent.com/6589200/115912245-0f34a200-a43d-11eb-83a5-b672cd3288d9.png)


And also the same issue when I uninstall from last time with the Doc IT Landscape not found message in Projects and Tasks.

**Comment by skaysurfer** [comment]
it worked for me- only missing a module in erpnext-13 with all IT related stuff, but the doctypes are usable!

Thank you!

**Comment by wojosc** [comment]
> it worked for me- only missing a module in erpnext-13 with all IT related stuff, but the doctypes are usable!
> 
> Thank you!

We will be updating to v13 friday. Possibly we will have to configure a Domain for IT Managment in the new structure seen in v13:
![grafik](https://user-images.githubusercontent.com/22279621/117141112-75f77b00-adae-11eb-80a8-687f64284f43.png)

We will keep you posted!

**Comment by wojosc** [comment]
hello everyone,

we have just tested the installation on frappecloud.com. it works fine. Closing this issue.
