### ISSUE TITLE
Unknown column 'tabMaintenance Visit.it_landscape' in 'where clause'

### ISSUE THREAD

**Issue by msperlinac** [tueit/it_management#223]
Does this support ERPNext v13?
I was able to install but nothing shows on the dashboard.
I can search for IT Landscape but I get this error when I try to save:

pymysql.err.OperationalError: (1054, "Unknown column 'tabMaintenance Visit.it_landscape' in 'where clause'")

**Comment by wojosc** [comment]
Hi @msperlinac the app supports v13, yes.

Please check out if you can find Configuration Item in search. That is the leading docType in this app.

We will look into your error posted when we find some time. Thanks for getting in touch!

**Comment by wojosc** [comment]
@msperlinac please head to the DocType Maintenance Visit and add a Custom field there with the Name "IT Landscape" Type "Link" and link to the DocType "IT Landscape".
