### ISSUE TITLE
Fresh V11 VM server and the error seems the same

### ISSUE THREAD

**Issue by Helkyd** [tueit/it_management#26]
![image](https://user-images.githubusercontent.com/20396898/67492220-fc85b500-f66d-11e9-9c3d-36d45846879a.png)

When installing... same problem.
How to fix?

**Comment by wojosc** [comment]
Sorry, I haven't had the chance to revise on this. Keep trying :)

**Comment by wojosc** [comment]
@Helkyd the app IT Management is only compatible for v12. There are no known issues with the installation at the moment. Please try it on v12. Thank you.
