### ISSUE TITLE
merging IT Ticket to Issue

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#32]
To make the app closer to core I suggest to merge IT Ticket into Issue. Most fields are already the same and a lot of usefull funktions are already implemented in Issue (like deleting the assignment when closed).

Let's discuss this over a meeting.

**Comment by wojosc** [comment]
der wird ersetzt. IT Ticket wird es theoretisch nirgends mehr geben.

**Comment by joelios** [comment]
Alles klar, dann werde ich den IT Ticket Type auch gleich entfernen, ok?

Mit freundlichen Grüssen
Joël Mesmer

**Comment by wojosc** [comment]
jupp

**Comment by wojosc** [comment]
passt, danke.

**Comment by joelios** [comment]
- [x] Step 1: replace all outgoing functions of IT Ticket to Issue (@joelios )
- [x] Step 2: replace all ingoing  functions of IT Ticket to Issue (@joelios )
- [ ] Step 3: Testing (@wojosc )
- [ ] Step 4: clean-up (@joelios )

**Comment by wojosc** [comment]
- [ ] Step 6: remove Purchase Order from Issue

**Comment by wojosc** [comment]
@joelios Please remove IT Ticket from Purchaseorder (and backlink)
