### ISSUE TITLE
Filter on IT Management Table

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#45]
There should be a filter-funktion vor the IT Management Table. This could look something like the "add multiple" in the table from Sales Order. And would be nice if it had more fields like when using the "get items from" button also in Sales Order (top right corner).

**Comment by wojosc** [comment]
Checkbox "Filter" befor IT Management Table with which the table is filtered for the customer in the Issue. Unchecking the box will give you all items from IT Management.

**Comment by wojosc** [comment]
![image](https://user-images.githubusercontent.com/22279621/74707283-aa1e6480-5219-11ea-805e-e4d09c7cea20.png)

Die Auswahl in Documents sollte nach dem Feld customer filtern (siehe Pfeil) weiter sollte es eine Checkbox an den stellen 1) oder 2) geben an welchen ich den Filter abschalten kann. Es gibt z.B. Räume in welchen IT Elemente mehrerer Kunden vorhanden sind.

**Comment by wojosc** [comment]
@joelios needs  Refresh "Strg+R" after Save to work. Please fix.

**Comment by joelios** [comment]
Please create in each doctype of dynamic_doctype a linkfield named "customer".

**Comment by wojosc** [comment]
@joelios all DocTypes inside IT Management now have the field "customer".

**Comment by joelios** [comment]
Siehe commit 0fafbf2
