### ISSUE TITLE
IT Checklist

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#48]
The possibilty to create a new DocType IT Checklist from a IT Management Table.

Case:
We create a checklist in Issue which shows a customer onboarding. Once this is done and approved it would be nice if I were able to merge the created IT Management Table which could then be a submittable DocType which I can use via "get from" for future reference.

We would use this for customer onboard, install configurations etc.

**Comment by joelios** [comment]
New Function "Get IT Management from > IT Checklist" implemented in dt Issue and dt IT Service Report

**Comment by wojosc** [comment]
![Bildschirmfoto von 2020-03-04 23-35-03](https://user-images.githubusercontent.com/22279621/75929504-0cf63980-5e71-11ea-9a37-895877ff3e2b.png)

@joelios please use frappe style guide and use same wording. In this case "Get Items from"

**Comment by joelios** [comment]
@wojosc das renaming kommt mit dem nächsten PR
