### ISSUE TITLE
Dashboard needs fix

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#56]
it_management/it_management/doctype/it_software/it_software_dashboard.py

dashboard throws error since implementation. It's visible, but it does not work.

**Comment by wojosc** [comment]
![grafik](https://user-images.githubusercontent.com/22279621/75761599-a1f61700-5d39-11ea-80e0-3d07478bbec1.png)

**Comment by joelios** [comment]
also fixed with #64

**Comment by wojosc** [comment]
error is fixed.
