### ISSUE TITLE
Anpassungen an IT Service Report und Add Activity

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#58]
Bei beiden DocTypes soll die Tabelle übertragen werden. Funktioniert bei IT Service Report bereits.

Bei beiden DocTypes soll das dahinterliegende Time Sheet gebucht (Status Gebucht statt Entwurf) werden.

**Comment by wojosc** [comment]
Tabellen fetchen erst einmal weglassen. Buchen der Time Sheets in beiden Funktionen direkt implementieren.

**Comment by joelios** [comment]
**IT Service Report**
Beim Speichern --> speichern Timesheet
Beim Buchen --> buchen Timesheet
Beim Stornieren --> stornieren Timesheet

**Add Activity (dt: Issue)**
Beim Speichern --> speichern & buchen Timesheet

**Comment by wojosc** [comment]
passt.
