### ISSUE TITLE
Software Configuration Item Title writeable

### ISSUE THREAD

**Issue by templis** [tueit/it_management#60]
We sometimes need to change a title of the Software Item Doctype to change something like SI-03055 to a more human writeable Title like ESET on Server2016"
![2020-02-18 14_05_52-Window](https://user-images.githubusercontent.com/9048398/74738860-0c965580-5258-11ea-9346-edd9b2236158.png)

**Comment by wojosc** [comment]
done https://github.com/tueit/it_management/commit/50893b12b72d64759b1f4aaf25a183a9a793958f
