### ISSUE TITLE
Doctype User Group needs some attention

### ISSUE THREAD

**Issue by templis** [tueit/it_management#61]
If you create a new User Group the title is something generic: 947300cebf and should be Groupname (eg. CEO)
![2020-02-18 17_15_57-Window](https://user-images.githubusercontent.com/9048398/74754926-a4a13880-5272-11ea-8ed4-516d244e2f77.png)
Also there should be the possibility to link User Accounts from the Doctype User Accounts furthermore it would be nice to add the User Group also in the User Account Doctype

**Comment by wojosc** [comment]
- [ ] Make Title usable https://github.com/tueit/it_management/commit/c2e0f45770c0ce48d5cd8f49343d75258e927300

**Comment by wojosc** [comment]
Du darfst das hier ruhig auf deutsch schreiben. Schließlich soll es ja vorangehen...

Das mit der User zu Gruppen zuordnung müssen wir mal noch richtig planen bevor ich da was reinbauen kann.

**Comment by wojosc** [comment]
Final touch ups in https://github.com/tueit/it_management/issues/65
