### ISSUE TITLE
Dashboard Issue

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#68]
- [x] Add Material Request

- [x] Remove Purchase Order

**Comment by wojosc** [comment]
@joelios es gibt noch kein Backlink zum DocType Issue im DocType Material Request. Habe diesen nun händisch nachgetragen. Projekt ist eine Ebene drinter in der Liste der Items. Vielleicht ist Issue dort ebenfalls besser plaziert.

**Comment by joelios** [comment]
@wojosc doch den hab ich hinzugefügt, siehe https://github.com/tueit/it_management/blob/4790bc87028bdcb4c9bab833e500fd580b668fab/it_management/it_management/custom/material_request.json#L21

wo hast Du diesen händisch nachgetragen? Soll ich das Linkfeld in das Lineitem zum Projekt verschieben?

**Comment by wojosc** [comment]
@joelios gucken wir auch nachher kurz drüber.
