### ISSUE TITLE
Kill autofetching Time Sheets

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#75]
In ERPNext when creating Sales Invoices and linking a Project it will auto-fetch all remaining Time Sheets from the project. Even when deleting these manually from the Sales Invoice they will be re-fetched on "Save".
We would like to have this turned off completely.

**Comment by joelios** [comment]
The function is located in lines 625 to 628 of the "sales_invoices.py" file. These lines must be commented out until the change is in the core.

**Comment by wojosc** [comment]
@joelios Please implement. We will have to work with the dependency to the other Issue

**Comment by wojosc** [comment]
Please create DocType for "IT Management Settings" with Section Sales Invoice and create a tick-box with the option to turn off the mentioned code. Please DocType in new section "Settings" (Einstellungen) in IT Management App.

**Comment by joelios** [comment]
@wojosc Please check this commit carefully

**Comment by joelios** [comment]
@wojosc lets try again

**Comment by wojosc** [comment]
@joelios Funktioniert! :+1:
