### ISSUE TITLE
"Get Items from" in Sales Invoice

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#77]
We would like to be able to fetch all Time Sheets from Issues, IT Service Reports, Tasks and Projects in DocType Sales Invoice.

**Comment by joelios** [comment]
Soloution will only work with https://github.com/tueit/it_management/issues/75#issuecomment-595697948

**Comment by wojosc** [comment]
@joelios Please remember to optimize: Under the button "Get Items from" we we wan't "Timesheet" which will open a multi-filter pop-up with "Project", "Task" and "Issue" (they should filter top-down).

**Comment by wojosc** [comment]
Please finish like seen in pictures of #69

**Comment by canlann** [comment]
Test: - [x] Pull no timesheets and submit
