### ISSUE TITLE
Dashboard von Solution soll IT-Backup link bekommen

### ISSUE THREAD

**Issue by templis** [tueit/it_management#79]
Wir brauchen genau wie bei den Config Items einen Link im Dashboard der Solutions
Wenn es geht, wäre es gut, wenn der Link nur dann im Dashboard auftaucht, wenn es sich um eine Backup Solution handelt.

**Comment by wojosc** [comment]
https://github.com/tueit/it_management/blob/master/it_management/it_management/doctype/solution/solution_dashboard.py
