### ISSUE TITLE
installation on vanilla production VM doesn't work

### ISSUE THREAD

**Issue by toneffectory** [tueit/it_management#85]
hi! I wanted to check out it_management app. So downloaded latest erpnext production build from `http://build.erpnext.com/ERPNext-Production.ova`
Running it in latest Virtualbox. In virtualbox's terminal I enter command
`bench get-app https://github.com/tueit/it_management.git`

and get following error:
![VirtualBox_ERPNext-Production-20190616131532_15_03_2020_23_15_44](https://user-images.githubusercontent.com/10992724/76711779-f4a8d900-6712-11ea-9745-2ef3f2a57604.png)

seemingly there's no directory apps in default home dir. So I tried creating it myself but then other errors popup...
![VirtualBox_ERPNext-Production-20190616131532_15_03_2020_23_17_11](https://user-images.githubusercontent.com/10992724/76711795-24f07780-6713-11ea-8c52-71c4b7039f10.png)

Please let me know what I'm doing wrong and how to solve this?

**Comment by wojosc** [comment]
Hi @toneffectory thank you for taking interest in the app.

Please upgrade your system to the latest version with 
`bench update --reset`
from the frappe-bench folder befor you install our app.

**Comment by toneffectory** [comment]
Hi @wojosc 
bench update didn't work either. So that made me thinking and I found the issue. It was me. User error...
So here for reference, in case anybody else is a user like me :-)

bench only works correctly if you cd into the frappe-bench dir. 
So to instal it_management:

`
cd ~/frappe-bench
bench get-app https://github.com/tueit/it_management.git
`

**Comment by wojosc** [comment]
Hi @toneffectory good work! I have updated our Wiki on this subject:
https://github.com/tueit/it_management/wiki/Installation

I'll close the issue. Thanks for your help.

**Comment by toneffectory** [comment]
Hi @wojosc 
unfortunately no luck yet. Getting the app now works, but not installing it using
`bench --site site1.local install-app it_management`

Screenshot of error:
<img width="823" alt="Schermafbeelding 2020-03-17 om 17 12 51" src="https://user-images.githubusercontent.com/10992724/76877312-7b74c780-6873-11ea-85f8-764c76c1cafa.png">

I also tried migrate and then install-app but still no luck. Anything else I can try?

**Comment by toneffectory** [comment]
so today I gave it another try. I noticed following. Most probably because I'm just very new to ERPNext, but perhaps also because things are maybe not as clear as it could have been.

I downloaded the erpnext production image (Virtual machine). It was the following document that caught my eye:
https://discuss.erpnext.com/t/release-erpnext-version-12/50986

according to this document, The master branch has been deprecated as of today i.e. 22 July, 2019. So apparently, the latest release (v12) is not the master but the development image. That could've be made more clear :-)

Anyway. All of the above issues are based on ERPNext: v11.1.38 (master), Frappe Framework: v11.1.35 (master).

I'll see if I can get ERPNext v12 working in virtual machine. So far no luck even starting ERPNext using  http://build.erpnext.com/ERPNext-Dev.ova

**Comment by wojosc** [comment]
@toneffectory installing ERPNext v12 can be tricky. There are many installation guides about though. Please check out discuss.erpnext.com for that matter.

**Comment by toneffectory** [comment]
@wojosc installation of ERPNext v12 done. Also verified that it_management app installations works correctly. Thanks.

**Comment by wojosc** [comment]
Thank you @toneffectory
