### ISSUE TITLE
Contact Card in Issue not working

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#87]
We used to have a contact card which would show the e-mailadress and phone number of the contact:
https://github.com/alyf-de/it_management/blob/master/it_management/it_management/doctype/it_ticket/it_ticket.js

```
render_contact: function (frm) {
		if (frm.doc.contact && frm.doc.hasOwnProperty('__onload')) {
			frappe.contacts.render_address_and_contact(frm);
			// hide "New Contact" Button
			$('.btn-contact').hide();
		} else {
			cur_frm.fields_dict.contact_html.html();
		}
	},
```

This does not work right now.

**Comment by joelios** [comment]
I can't reproduce the error

![grafik](https://user-images.githubusercontent.com/26505401/78672591-290e5000-78e1-11ea-9316-d1e76eb1792a.png)

**Comment by wojosc** [comment]
@joelios the problem is found in Issue, not in IT Ticket. IT Ticket is basicly depricated and does not need any further development. Please have a quick look again. Thanks.
