### ISSUE TITLE
Changes to "Make Time Sheet"

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#98]
- [ ] need to be able to add brakes

- [ ] Move fields.  To-Time should be after Description.

![image](https://user-images.githubusercontent.com/22279621/80811079-79698c80-8bc5-11ea-8ba2-5fdb7f09f5c7.png)

**Comment by musketeer90** [comment]
add_activity() has been moved to itm_utils.js

**Comment by musketeer90** [comment]
Done
