### ISSUE TITLE
Verbesserung einer Tablle

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#99]
<img width="585" alt="grafik" src="https://user-images.githubusercontent.com/22279621/81387056-58012700-9116-11ea-8faf-fd8b938aa0d0.png">
können wir hier das Spacing verbessern?

**Comment by musketeer90** [comment]
Welches Doctype ist das?

**Comment by wojosc** [comment]
@musketeer90 da geht es um "Get IT Checklist" aus Issue heraus.

**Comment by canlann** [comment]
Compare #119
